name: "Create docker image and zip."

env:
  PROJECT_ID: nettikauppasimulaattori
  REGION: europe-north1
  REPOSITORY: nettikauppasimulaattori
  IMAGE_TAG: nettikauppasimulaattori_simulator:latest

on:
  workflow_dispatch:

  push:
    branches:
      - main
      - devel # Enable for debugging the workflow file.

jobs:
  build_push_docker_image:
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Authenticate to google cloud."
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY }}"

      - name: "Set up Google Cloud SDK."
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
          project_id: ${{env.PROJECT_ID}}

      - name: "Check google cloud CLI works."
        run: "gcloud info"

      - name: "Docker auth to gcloud."
        run: gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev --quiet

      - name: Setup Docker buildx.
        uses: docker/setup-buildx-action@v3

      - name: Write secret to file
        run: echo ${{ secrets.GCLOUD_BIGQUERY_FROM_DOCKER_KEY }} >> simulator/ap.json

      - name: Build Docker-image.
        run: |
          docker buildx build -t ${{env.IMAGE_TAG}} --load simulator

      - name: Push to gcloud artifact registery
        run: |
          docker tag ${{env.IMAGE_TAG}} ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE_TAG}}
          docker push ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE_TAG}}
