name: Create zip of simulator-source code and upload to google-cloud-storage.

on:
  push:
    branches:
      - main
      # - ci_zip

env:
  WIF_PROVIDER: projects/63753790271/locations/global/workloadIdentityPools/github-pool/providers/github
  WIF_SERVICE_ACCOUNT: github-actions@github-actions-temp.iam.gserviceaccount.com

  #   WIF_PROVIDER: projects/725245772054/locations/global/workloadIdentityPools/github-actions/providers/github
  #   WIF_SERVICE_ACCOUNT: github-connection@nettikauppasimulaattori.iam.gserviceaccount.com
#
jobs:
  create_zip:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: simulator

    steps:
      - uses: actions/checkout@v4

      - name: Create zip-file.
        # zip every file except testing_files.
        run: zip nettikauppasimulaattori.zip `find ! -name "*_test.go" -type f`

      - name: Save zip-file.
        uses: actions/upload-artifact@v4
        with:
          name: zip-artifact
          path: simulator/nettikauppasimulaattori.zip
          retention-days: 1

  upload_zip:
    runs-on: ubuntu-latest
    needs: create_zip
    permissions:
      contents: "read"
      id-token: "write"

    defaults:
      run:
        working-directory: simulator

    steps:
      - uses: actions/checkout@v4

      - name: "Authenticate to google cloud."
        uses: "google-github-actions/auth@v1"
        with:
          create_credentials_file: true
          # workload_identity_provider: ${{secrets.WIF_PROVIDER}}
          # service_account: ${{secrets.WIF_SERVICE_ACCOUNT}}
          workload_identity_provider: ${{env.WIF_PROVIDER}}
          service_account: ${{env.WIF_SERVICE_ACCOUNT}}

      - name: "Set up Google Cloud SDK."
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          version: ">= 363.0.0"
          project_id: nettikauppasimulaattori

      - name: "Check google cloud cli works."
        run: "gcloud info"

      - name: Get saved zip-file.
        uses: actions/download-artifact@v2
        with:
          name: zip-artifact
          path: simulator/nettikauppasimulaattori.zip

      - name: Upload to google-cloud-storage.
        uses: google-github-actions/upload-cloud-storage@v1
        with:
          path: simulator/nettikauppasimulaattori.zip
          destination: functions_source_code/nettikauppasimulaattori
