# name: "Create docker image."
# 
# env:
#   PROJECT_ID: nettikauppasimulaattori
#   REGION: europe-north1
#   # REPOSITORY: nettikauppasimulaattori
#   REPOSITORY: testirepo
#   IMAGE_TAG: nettikauppasimulaattori_simulator:latest
#   WIF_PROVIDER: projects/725245772054/locations/global/workloadIdentityPools/github-actions/providers/github
#   WIF_SERVICE_ACCOUNT: github-connection@nettikauppasimulaattori.iam.gserviceaccount.com
#   # WIF_SERVICE_ACCOUNT: artifact-repo-docker@nettikauppasimulaattori.iam.gserviceaccount.com
# 
# on:
#     push:
#         branches:
#          - main
#          - docker # Enable for debugging the workflow file.
#     
# jobs:
#   build_docker_image:
#     runs-on: ubuntu-latest
#   
#     steps:
#      - uses: actions/checkout@v4
# 
#      - name: Setup QEMU.
#        uses: docker/setup-qemu-action@v3
# 
#      - name: Setup Docker buildx.
#        uses: docker/setup-buildx-action@v3
# 
# #      - name: Create Docker image.
# #        uses: docker/build-push-action@v5
# #        with:
# #          context: .
# #          push: false
# #          tags: app:latest
# 
#      - name: Build Docker-image.
#        run: |
#          docker buildx build -t ${{env.IMAGE_TAG}} --load simulator
#          mkdir -p docker-tmp
#          docker save ${{env.IMAGE_TAG}} > docker-tmp/docker-image.tar
# 
#      - name: Save Docker-image.
#        uses: actions/upload-artifact@v2
#        with:
#          name: docker-artifact
#          path: docker-tmp
#          retention-days: 1
# 
# 
#   Push_image_to_gcloud:
#     runs-on: ubuntu-latest
#     needs: build_docker_image
#     permissions:
#       contents: 'read'
#       id-token: 'write'
#    
#     steps:
#      - uses: actions/checkout@v4
# 
#      - name: 'Authenticate to google cloud.'
#        uses: 'google-github-actions/auth@v1'
#        with:
#          create_credentials_file: true
#          workload_identity_provider: ${{env.WIF_PROVIDER}}
#          service_account: ${{env.WIF_SERVICE_ACCOUNT}}
# 
#      - name: 'Set up Google Cloud SDK.'
#        uses: 'google-github-actions/setup-gcloud@v1'
#        with:
#          version: '>= 363.0.0'
#          project_id: ${{env.PROJECT_ID}}
#    
#      - name: 'Check google cloud cli works.'
#        run: 'gcloud info'
# 
#      - name: "Docker auth to gcloud."
#        run: gcloud auth configure-docker ${{env.REGION}}-docker.pkg.dev --quiet
# 
#      - name: Get saved Docker-image
#        uses: actions/download-artifact@v2
#        with:
#          name: docker-artifact
#          path: docker-tmp
#      - name: Load Docker-image
#        run: |
#          docker load < docker-tmp/docker-image.tar
# 
#      - name: Push to gcloud artifact registery
#        run: |
#          docker tag ${{env.IMAGE_TAG}} ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE_TAG}}
#          docker push ${{env.REGION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE_TAG}}
