name: nettikauppasimulaattori automated testing

on:
  push:
    branches:
      - "*"
      - "**"
      - "!main"

jobs:
  test_simulator:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: simulator

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go.
        uses: actions/setup-go@v4
        with:
          # working-directory does not work for these???
          go-version-file: "simulator/go.mod"
          cache-dependency-path: "simulator/go.sum"

      # setup-go already displays version.
      # - name: Check Go version.
      #   run: go version

      - name: Compile.
        run: go build

      - name: Run tests.
        run: go test
